name: running_on_dart
version: 1.0.0
description: Discord Bot for nyxx development
author: Szymon Uglis <szymon.uglis@tuta.io>
homepage: https://github.com/l7ssha/running_on_dart
repository: https://github.com/l7ssha/running_on_dart
documentation: https://github.com/l7ssha/nyxx/running_on_dart
issue_tracker: https://github.com/l7ssha/nyxx/running_on_dart

environment:
  sdk: '>=2.12.0-51.0.dev <3.0.0'

dependencies:
  logging: "^1.0.0"
  time_ago_provider:
    git:
      url: git://github.com/l7ssha/time_ago_provider.git
  nyxx: "^1.1.0-dev.5"
  nyxx_commander: "^1.1.0-dev.5"
